schema:

  \SeachCacheData:
    version: 10001
    columns:
      isBlocked:
        type: Integer
        column: 'is_blocked_accommodation'
        length: 1
      booleanMask:
        type: BitMask
        columns:
          - is_blocked_accommodation
          - is_allowed
          - is_price
        length: 32

